---
title: Starter pack Systemic study
---
graph LR
    subgraph IAGenerative
        A1["Utilisation Starter Pack"] -- S --> B1["Qualité des prompts"]
        B1 -- S --> C1["Résultats efficaces"]
        C1 -- S --> A1
    end
    
    subgraph ReseauxSociaux
        L1["Publication reseaux sociaux"]
        L1 -- S --> M1["Commentaires positifs"]
        L1 -- S --> M2["Commentaires negatifs"]
        M2 -- O --> L1
        M1 -- S --> L1
		end

	  subgraph Fournisseurs
        J1["Augmentation données d'entraînement"]
        J1 -- S --> K1["Amélioration modèles"]
        J1 -- S --> O1["Recours aux modérateurs"] 
        O1 -- S --> K1
    end


    subgraph Creativite
        D1["Dépendance aux prompts"] -- S --> E1["Standardisation"]
        E1 -- S --> F1["Perte de créativité"]
        E1 -- S --> F2["Perte de compétences critiques"]
        F1 -- S --> D1
    end

    subgraph "Ressources"
        G1["Consommation ressources"] -- S --> H1["Coûts opérationnels"]
        H1 -- S --> I1["Barrières d'accès"]
        I1 -- O --> G1
    end
   
	 subgraph "Droits"
        N1["Respect du droit d'auteur"] 
        P1["Esclaves du web"] 
    end

    %% Connexions inter-systèmes
		IAGenerative -- S --> Fournisseurs
		Fournisseurs -- S --> IAGenerative
		IAGenerative -- O --> Creativite
		Fournisseurs -- O --> Droits
		IAGenerative -- O --> Ressources
		Fournisseurs -- O --> Ressources
		ReseauxSociaux -- O --> IAGenerative
		ReseauxSociaux -- S --> IAGenerative
		Droits -- S --> M2						
		Ressources -- S --> M2
		Creativite -- O --> IAGenerative

%% S = Boucle de renforcement (positive)
  %% O = Boucle d'équilibrage (négative)
