---
title: Starter pack Systemic study
---
graph LR
    subgraph IAGenerative
        A1["Utilisation Starter Pack"] -- S --> B1["Qualité des prompts"]
        B1 -- S --> C1["Résultats efficaces"]
        C1 -- S --> A1
    end

    subgraph SatisfactionImmediate
        E3["Validation sociale"] -- S --> F3["Dopamine"]
        F3 -- S --> G3["Désir de publication"]
        G3 -- S --> E3
		end

    subgraph SatisfactionDurable
				I4["Accomplissement"]
        I4 -- S --> J4["Confort"]
		end


	
		subgraph Anxiete
        E4["Anxiete écologique"] 
        F4["Anxiete sociale"]
    end
    
    subgraph ReseauxSociaux
        L1["Publication reseaux sociaux"]
        L1 -- S --> B2["Obtention de likes"]
        B2 -- S --> C2["Sentiment de reconnaissance"]
        C2 -- S --> D2["Augmentation de l'engagement"]
        D2 -- S --> L1
		end

	  subgraph Fournisseurs
        J1["Augmentation données d'entraînement"]
        J1 -- S --> K1["Amélioration modèles"]
        J1 -- S --> O1["Recours aux modérateurs"] 
        O1 -- S --> K1
    end


    subgraph Creativite
        D1["Dépendance aux prompts"] -- S --> E1["Standardisation"]
        E1 -- S --> F1["Perte de créativité"]
        E1 -- S --> F2["Perte de compétences critiques"]
        F1 -- S --> D1
        H4["Expression personnelle"] 
        F1 -- O --> H4
        F2 -- O --> H4      
    end

    subgraph Ressources
        G1["Consommation ressources"] -- S --> H1["Coûts opérationnels"]
        H1 -- S --> I1["Barrières d'accès"]
        I1 -- O --> G1
    end
   
	 subgraph Droits
        N1["Respect du droit d'auteur"] 
        P1["Respect des droits humains"] 
    end

    %% Connexions inter-systèmes
		IAGenerative -- S --> Fournisseurs
		IAGenerative -- S --> SatisfactionImmediate
		Fournisseurs -- S --> IAGenerative
		IAGenerative -- O --> Creativite
		Fournisseurs -- O --> Droits
		IAGenerative -- O --> Ressources
		Fournisseurs -- O --> Ressources
		ReseauxSociaux -- S --> IAGenerative
		SatisfactionImmediate -- S --> IAGenerative
		SatisfactionImmediate -- S --> ReseauxSociaux
   	ReseauxSociaux -- S --> SatisfactionImmediate
		IAGenerative -- S --> ReseauxSociaux
		Creativite -- O --> IAGenerative
		SatisfactionDurable -- S --> Creativite
		Ressources -- S --> E4
		Droits -- S --> F4
		H4 -- S --> I4
		Anxiete -- O --> J4

%% S = Boucle de renforcement (positive)
%% O = Boucle d'équilibrage (négative)
